/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#fefcff',
        'on-secondary': '#ffffff',
        'surface-bright': '#faf9fe',
        'on-error-container': '#93000a',
        'secondary': '#006e28',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#004493',
        'inverse-surface': '#2f3034',
        'on-secondary-fixed-variant': '#00531c',
        'secondary-fixed-dim': '#53e16f',
        'surface-container': '#eeedf3',
        'on-tertiary-container': '#fffbff',
        'background': '#faf9fe',
        'on-tertiary-fixed-variant': '#930005',
        'on-primary-fixed': '#001a41',
        'error-container': '#ffdad6',
        'primary-container': '#0070eb',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#002107',
        'surface-container-low': '#f4f3f8',
        'surface-container-high': '#e9e7ed',
        'error': '#ba1a1a',
        'on-secondary-container': '#00732a',
        'outline': '#717786',
        'tertiary': '#bc000a',
        'primary-fixed-dim': '#adc6ff',
        'surface-variant': '#e3e2e7',
        'primary': '#0058bc',
        'on-surface-variant': '#414755',
        'on-tertiary-fixed': '#410001',
        'on-error': '#ffffff',
        'secondary-fixed': '#72fe88',
        'surface': '#faf9fe',
        'inverse-primary': '#adc6ff',
        'surface-dim': '#dad9df',
        'tertiary-fixed-dim': '#ffb4aa',
        'outline-variant': '#c1c6d7',
        'on-surface': '#1a1b1f',
        'tertiary-fixed': '#ffdad5',
        'surface-container-highest': '#e3e2e7',
        'on-background': '#1a1b1f',
        'surface-tint': '#005bc1',
        'tertiary-container': '#e2241f',
        'secondary-container': '#6ffb85',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#d8e2ff',
        'inverse-on-surface': '#f1f0f5',
      },
      fontFamily: {
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
